# This workflow builds an ot3 image

name: 'Build OT3 image'
on:
  push:
    branches:
      - '*'
  workflow_dispatch:

jobs:
  build-image:
    name: 'build ot3 image'
    runs-on: 'ubuntu-20.04'
    steps:
      - uses: 'actions/checkout@v2'
      - name: 'build docker image'
        run: |
          mkdir -p docker/oe-core/build
          cd docker
          cp ../start.sh ./
          cp ../Dockerfile ./
          cp ../*.patch ./
          docker build --tag "ot3-image:latest" ./Dockerfile
      - name: 'build ot3 image'
        run: |
          cd docker
          docker run -it --rm -v $PWD/oe-core/build:/home/ot3/oe-core/build/deploy ot3-image:latest
      - uses: 'actions/upload-artifact@v2'
        with:
          name: 'ot3-image'
          path: './docker/oe-core/build/*'
