# Ensures that when a pull request occurs, a branch matching the name of
# the branch being pulled from is created in oe-core. Because oe-core's
# submodule update machinery tries to check out a matching branch name,
# this will cause builds of oe-core on that branch to pull this branch of
# this repo.

name: 'Build OT3 Image'

on:
  pull_request:
    types: [opened, reopened, synchronize]
    branches:
      - '*'
  workflow_dispatch:

jobs:
  branch-and-build:
    name: 'Ensure a matching branch exists in oe-core then build'
    runs-on: 'ubuntu-18.04'
    steps:
      - name: 'Format head ref properly'
        run: |
          echo "::set-output name=refname::${GITHUB_HEAD_REF#refs/}"
          echo "::set-output name=branchname::${GITHUB_HEAD_REF#refs/heads/}"
          echo "::set-output name=pullnumber::${GITHUB_REF#refs/pulls/}"
        id: head-ref
      - name: 'Check if matching branch oe-core/${{ steps.head-ref.outputs.refname}} exists'
        continue-on-error: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        uses: octokit/request-action@v2.x
        id: check-matching-branch
        with:
          route: GET /repos/{owner}/{repo}/git/ref/{ref}
          owner: opentrons
          repo: oe-core
          ref: heads/${{github.head_ref}}
      - name: 'Create branch: pulling oe-core'
        if: ${{ steps.check-matching-branch.outputs.status != 200 }}
        uses: actions/checkout@v2
        with:
          depth: 1
          repo: opentrons/oe-core
          token: ${{ secrets.CROSSREPO_GH_TOKEN }}
          ref: main
          path: oe-core
      - name: 'making branch and changing submodule ref'
        if: ${{ steps.check-matching-branch.outputs.status != 200 }}
        env:
          GITHUB_TOKEN: ${{ secrets.CROSSREPO_GH_TOKEN }}
        run: |
          cd oe-core
          git checkout -b ${{ steps.head-ref.outputs.branchname }}
          git submodule set-branch -b ${{ steps.head-ref.outputs.branchname }} layers/meta-opentrons
          git commit -m << EOF
          layers/meta-opentrons: ${{steps.head-ref.outputs.branchname}}

          This is an automated commit that sets the tracking-branch of the meta-opentrons
          submodule to the branch being used in
          https://github.com/opentrons/meta-opentrons/pulls/${{steps.head-ref.pullnumber}}
          EOF
          git push --set-upstream origin ${{ steps.head-ref.outputs.branchname }}

      - name: 'Branch ${{ steps.head-ref.outputs.branchname }} exists, nothing to do'
        if: ${{ steps.check-matching-branch.outputs.status == 200 }}
        run: echo ""

      - name: 'Start build'
        env:
          GITHUB_TOKEN: ${{ secrets.CROSSREPO_GH_TOKEN }}
        uses: octokit/request-action@v2.x
        with:
          route: POST /repos/{owner}/{repo}/actions/workflows/{workflow_id}/dispatches
          owner: opentrons
          repo: oe-core
          workflow_id: build-ot3.yml
          ref: ${{ steps.head-ref.outputs.refname }}
