# Ensures that when a pull request occurs, a branch matching the name of
# the branch being pulled from is created in oe-core. Because oe-core's
# submodule update machinery tries to check out a matching branch name,
# this will cause builds of oe-core on that branch to pull this branch of
# this repo.

name: 'Build OT3 Image'

on:
  pull_request:
    types: [opened, reopened, synchronize]
    branches:
      - '*'
  workflow_dispatch:

jobs:
  setup-branch:
    name: 'Ensure a matching branch exists in oe-core'
    runs-on: 'ubuntu-18.04'
    steps:
      - name: 'Format head ref properly'
        run: |
          echo "::set-output name=refname::${GITHUB_HEAD_REF#refs/}"
          echo "::set-output name=branchname::${GITHUB_HEAD_REF#refs/heads/}"
        id: head-ref
      - name: 'Check if matching branch oe-core/${{ steps.head-ref.outputs.refname}} exists'
        continue-on-error: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        uses: octokit/request-action@v2.x
        id: check-matching-branch
        with:
          route: GET /repos/{owner}/{repo}/git/ref/{ref}
          owner: opentrons
          repo: oe-core
          ref: heads/${{github.head_ref}}
      - name: 'Creating matching branch: Finding head of oe-core/main'
        if: ${{ steps.check-matching-branch.outputs.status != 200 }}
        id: get-oe-core-main-head
        env:
          GITHUB_TOKEN: ${{ secrets.CROSSREPO_GH_TOKEN }}
        uses: octokit/request-action@v2.x
        with:
          route: GET /repos/{owner}/{repo}/git/ref/{ref}
          owner: opentrons
          repo: oe-core
          ref: heads/main
      - name: 'Creating matching branch oe-core/${{steps.head-ref.outputs.refname}}'
        if: ${{ steps.check-matching-branch.outputs.status != 200 }}
        env:
          GITHUB_TOKEN: ${{ secrets.CROSSREPO_GH_TOKEN }}
        uses: octokit/request-action@v2.x
        with:
          route: POST /repos/{owner}/{repo}/git/refs
          owner: opentrons
          repo: oe-core
          ref: refs/heads/${{ github.head_ref }}
          sha: "${{ fromJSON(steps.get-oe-core-main-head.outputs.data).object.sha }}"
      - name: 'Branch oe-core/${{github.head_ref}} already exists, nothing to do'
        if: ${{ steps.check-matching-branch.outputs.status == 200 }}
        run: echo ""
  run-build:
    name: 'Build the branch'
    runs-on: 'ubuntu-18.04'
    needs: setup-branch
    timeout-minutes: 480
    steps:
      - name: 'Format head ref properly'
        run: |
          echo "::set-output name=refname::${GITHUB_HEAD_REF#refs/}"
          echo "::set-output name=branchname::${GITHUB_HEAD_REF#refs/heads/}"
        id: head-ref
      - name: Set AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}
      - name: Run CodeBuild
        id: codebuild
        uses: aws-actions/aws-codebuild-run-build@v1.0.3
        env:
          GITHUB_SHA: ${{ github.head_ref }}
        with:
          project-name: ${{ secrets.AWS_CODEBUILD_PROJECT_NAME }}
      - name: Post results
        uses: slackapi/slack-github-action@v1.14.0
        with:
          payload: "{\"s3-url\":\"https://s3.console.aws.amazon.com/s3/buckets/ot3-builds?prefix=${{ steps.codebuild.outputs.aws-build-id }}/\",\"type\":\"branch in meta-opentrons\", \"reflike\":\"${{ github.head_ref }}\", \"image\":\"https://d2irdh6zupqygx.cloudfront.net/${{steps.codebuild.outputs.aws-build-id}}/ot3-oe/opentrons/toradex-minimal.tar\"}"
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
