# Starts builds based on recent merges to main

name: 'Build OT3 Image'

on:
  push:
    branches:
      - 'main'
  workflow_dispatch:

jobs:
  build:
    name: 'Start an upstream build'
    runs-on: 'ubuntu-18.04'
    steps:
      - name: 'Start build'
        env:
          GITHUB_TOKEN: ${{ secrets.CROSSREPO_GH_TOKEN }}
        uses: octokit/request-action@v2.x
        with:
          route: POST /repos/{owner}/{repo}/actions/workflows/{workflow_id}/dispatches
          owner: opentrons
          repo: oe-core
          workflow_id: build-ot3.yml
          ref: main
