# Kick off a build of the ot3 system on pushes to branches with matching names
# in oe-core

name: 'Build OT-3 Image'

on:
  push:
    branches:
      - '*'
    # Make sure that if you remove this you alter the branch creation logic,
    # which will otherwise be able to create tags
    tags-ignore:
      - '*'
  workflow_dispatch:

jobs:
  invoke-builds:
    name: 'Start build if possible'
    runs-on: 'ubuntu-18.04'
    steps:
      - name: 'Format head ref properly'
        run: echo "::set-output name=refname::${GITHUB_REF#refs/}"
        id: head-ref
      - name: 'Check if matching branch exists in oe-core'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        uses: octokit/request-action@v2.x
        continue-on-error: true
        id: check-matching-branch
        with:
          route: GET /repos/{owner}/{repo}/git/ref/{ref}
          owner: opentrons
          repo: oe-core
          ref: ${{ steps.head-ref.outputs.refname }}
      - name: 'Branch not yet created; open a pull request for automated builds'
        if: ${{ steps.check-matching-branch.outputs.status != 200 }}
        run: echo ""
      - name: Run CodeBuild
        if: ${{ steps.check-matching-branch.outputs.status == 200 }}
        id: codebuild
        uses: aws-actions/aws-codebuild-run-build@v1.0.3
        env:
          GITHUB_SHA: ${{ fromJSON(steps.check-matching-branch.outputs.data) && fromJSON(steps.check-matching-branch.outputs.data).object && fromJSON(steps.check-matching-branch.outputs.data).sha }}
        with:
          project-name: ${{ secrets.AWS_CODEBUILD_PROJECT_NAME }}
      - name: Post results
        if: ${{ steps.check-matching-branch.outputs.status == 200 }}
        uses: slackapi/slack-github-action@v1.14.0
        with:
          payload: "{\"s3-url\":\"https://s3.console.aws.amazon.com/s3/buckets/ot3-builds?prefix=${{ steps.codebuild.outputs.aws-build-id }}/\",\"type\":\"branch in meta-opentrons\", \"reflike\":\"${{ github.ref }}\", \"image\":\"https://d2irdh6zupqygx.cloudfront.net/${{steps.codebuild.outputs.aws-build-id}}/ot3-oe/opentrons/toradex-minimal.tar\"}"
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
